#---
# name: huggingface_hub
# group: llm
# depends: [python]
# test: test.py
# notes: provides `huggingface-cli` and `huggingface-downloader` tools
#---
ARG BASE_IMAGE=kairin/001:2025-03-25-0404
FROM ${BASE_IMAGE}

# set the model cache dir
ENV TRANSFORMERS_CACHE=/data/models/huggingface \
    HUGGINGFACE_HUB_CACHE=/data/models/huggingface \
    HF_HOME=/data/models/huggingface

# add downloader tool
COPY huggingface-downloader /usr/local/bin/
COPY huggingface-downloader.py /usr/local/bin/_huggingface-downloader.py

# install huggingface_hub package (with CLI)
RUN set -ex \
    # Fix: ModuleNotFoundError: No module named 'dataclasses' (on JetPack 4) \
    && pip3 install \
        huggingface_hub[cli] \
        dataclasses \
    \
    # make sure it loads \
    && huggingface-cli --help \
    && huggingface-downloader --help \
    && pip3 show huggingface_hub \
    && python3 -c 'import huggingface_hub; print(huggingface_hub.__version__)' \
    \
    # for benchmark timing \
    && apt-get update \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean
