#!/usr/bin/env bash
set -e

ROOT="$(dirname "$(readlink -f "$0")")"
DEVPI_DIR="${ROOT}/packages/net/devpi"
CONTAINER_NAME="devpi-local"
IMAGE_NAME="devpi-local"

if [ -f "${ROOT}/.env" ]; then
    set -a
    source "${ROOT}/.env"
    set +a
fi

DEVPI_PORT="${DEVPI_PORT:-3141}"
DEVPI_PASSWORD="${DEVPI_PASSWORD:-123}"
DEVPI_USER_PASSWORD="${DEVPI_USER_PASSWORD:-123}"
DEVPI_URL="http://localhost:${DEVPI_PORT}"
DEVPI_CACHE="${DEVPI_CACHE:-${ROOT}/packages/net/devpi/cache}"

devpi_exec() {
    docker exec "${CONTAINER_NAME}" "$@"
}

wait_for_server() {
    local max=60
    for i in $(seq 1 "${max}"); do
        if curl -sf "${DEVPI_URL}/+api" >/dev/null 2>&1; then
            return 0
        fi
        printf "\r  waiting for devpi server... (%d/%d)" "$i" "$max"
        sleep 2
    done
    echo ""
    echo "ERROR: devpi server did not become ready within ${max} attempts"
    docker logs "${CONTAINER_NAME}" 2>&1 | tail -30
    exit 1
}

echo "========================================="
echo " Launching local PyPI (devpi) server"
echo "========================================="

echo ""
echo "==> Building Docker image from ${DEVPI_DIR}..."
docker build -t "${IMAGE_NAME}" "${DEVPI_DIR}"

docker rm -f "${CONTAINER_NAME}" 2>/dev/null || true
mkdir -p "${DEVPI_CACHE}"

echo ""
echo "==> Starting devpi container on port ${DEVPI_PORT}..."
docker run -d \
    --name "${CONTAINER_NAME}" \
    --restart unless-stopped \
    -p "${DEVPI_PORT}:3141" \
    -v "${DEVPI_CACHE}:/devpi" \
    -v "${DEVPI_DIR}/blacklist.txt:/etc/devpi/blacklist.txt:ro" \
    -e DEVPI_PASSWORD="${DEVPI_PASSWORD}" \
    -e DEVPISERVER_SERVERDIR=/devpi \
    -e DEVPI_MIRROR_BLACKLIST=/etc/devpi/blacklist.txt \
    "${IMAGE_NAME}"

echo ""
echo "==> Waiting for devpi server to come online..."
wait_for_server
echo ""
echo "    devpi server is ready at ${DEVPI_URL}"

# ── Configure server (first run only) ───────────────────────────────
CONFIGURED_MARKER="${DEVPI_CACHE}/.configured"

if [ ! -f "${CONFIGURED_MARKER}" ]; then
    echo ""
    echo "==> Configuring devpi server (first run)..."

    devpi_exec devpi use http://localhost:3141
    devpi_exec devpi login root --password "${DEVPI_PASSWORD}"

    # Disable local file storage for packages fetched from upstream PyPI
    devpi_exec devpi index root/pypi mirror_use_external_urls=true

    # Centralized index that all user indexes inherit from
    echo "    Creating root/dev-pypi..."
    devpi_exec devpi index -c root/dev-pypi bases=root/pypi mirror_whitelist='*'

    # Create users
    echo "    Creating users: jp6, jp7, sbsa, amd64..."
    for user in jp6 jp7 sbsa amd64; do
        devpi_exec devpi user -c "${user}" "password=${DEVPI_USER_PASSWORD}"
    done

    # JP6 indexes
    echo "    Creating jp6/cu126..."
    devpi_exec devpi login jp6 --password "${DEVPI_USER_PASSWORD}"
    devpi_exec devpi index -c jp6/cu126 bases=root/dev-pypi

    echo "    Creating jp6/cu129..."
    devpi_exec devpi login jp6 --password "${DEVPI_USER_PASSWORD}"
    devpi_exec devpi index -c jp6/cu129 bases=root/dev-pypi

    # JP7 indexes
    echo "    Creating jp7/cu132..."
    devpi_exec devpi login jp7 --password "${DEVPI_USER_PASSWORD}"
    devpi_exec devpi index -c jp7/cu132 bases=root/dev-pypi

    # SBSA indexes
    echo "    Creating sbsa/cu130, sbsa/cu132..."
    devpi_exec devpi login sbsa --password "${DEVPI_USER_PASSWORD}"
    devpi_exec devpi index -c sbsa/cu130 bases=root/dev-pypi
    devpi_exec devpi index -c sbsa/cu132 bases=root/dev-pypi

    # AMD64 indexes
    echo "    Creating amd64/cu132..."
    devpi_exec devpi login amd64 --password "${DEVPI_USER_PASSWORD}"
    devpi_exec devpi index -c amd64/cu132 bases=root/dev-pypi

    touch "${CONFIGURED_MARKER}"
    echo "    Configuration complete!"
else
    echo ""
    echo "==> Server already configured (found ${CONFIGURED_MARKER})."
    echo "    Delete that file and re-run to force reconfiguration."
fi

# ── Update .env with local PyPI settings ────────────────────────────
ENV_FILE="${ROOT}/.env"
MARKER_START="# --- LOCAL PYPI (devpi) --- auto-generated by launch_pypi.sh ---"
MARKER_END="# --- END LOCAL PYPI ---"

if [ -f "${ENV_FILE}" ]; then
    awk -v start="${MARKER_START}" -v end="${MARKER_END}" '
        $0 == start { skip=1; next }
        $0 == end   { skip=0; next }
        !skip
    ' "${ENV_FILE}" > "${ENV_FILE}.tmp"
    mv "${ENV_FILE}.tmp" "${ENV_FILE}"
fi

cat >> "${ENV_FILE}" <<EOF

${MARKER_START}
DEVPI_URL=${DEVPI_URL}
DEVPI_PORT=${DEVPI_PORT}
DEVPI_PASSWORD=${DEVPI_PASSWORD}
DEVPI_USER_PASSWORD=${DEVPI_USER_PASSWORD}
LOCAL_PIP_INDEX_URL=${DEVPI_URL}/jp6/cu126/+simple/
PIP_UPLOAD_REPO=${DEVPI_URL}/jp6/cu126/
PIP_UPLOAD_HOST=localhost:${DEVPI_PORT}
${MARKER_END}
EOF

echo ""
echo "==> Updated ${ENV_FILE} with local PyPI settings"

# Re-source .env so the current shell picks up the new values
set -a
source "${ENV_FILE}"
set +a

echo ""
echo "========================================="
echo " Local PyPI server is running!"
echo "========================================="
echo ""
echo " Server:    ${DEVPI_URL}"
echo " Container: ${CONTAINER_NAME}"
echo ""
echo " Available indexes:"
echo "   jp6/cu126   -> ${DEVPI_URL}/jp6/cu126/+simple/"
echo "   jp6/cu129   -> ${DEVPI_URL}/jp6/cu129/+simple/"
echo "   jp7/cu132   -> ${DEVPI_URL}/jp7/cu132/+simple/"
echo "   sbsa/cu130  -> ${DEVPI_URL}/sbsa/cu130/+simple/"
echo "   sbsa/cu132  -> ${DEVPI_URL}/sbsa/cu132/+simple/"
echo "   amd64/cu132 -> ${DEVPI_URL}/amd64/cu132/+simple/"
echo ""
echo " To switch index, update LOCAL_PIP_INDEX_URL in .env:"
echo "   LOCAL_PIP_INDEX_URL=${DEVPI_URL}/sbsa/cu130/+simple/"
echo ""
echo " Upload wheels with twine:"
echo "   twine upload --repository-url ${DEVPI_URL}/<user>/<index>/ dist/*.whl"
echo ""
