name: 🐛 Bug Report
# title: " "
description: Problems with jetson-containers
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting an jetson-containers 🐛 Bug Report!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the jetson-containers [Jetson PlayGround](https://www.jetson-ai-lab.com/), [Jetson Forum](https://forums.developer.nvidia.com/c/agx-autonomous-machines/jetson-embedded-systems/70) and [issues](https://github.com/dusty-nv/jetson-containers/issues) to see if a similar feature request already exists.
      options:
        - label: >
            I have searched the jetson-containers [issues](https://github.com/dusty-nv/jetson-containers/issues) and found no similar feature requests.
          required: true

  - type: dropdown
    attributes:
      label: jetson-containers Component
      description: |
        Please select the jetson-containers component where you found the bug.
      multiple: true
      options:
        - "JetPack"
        - "CUDA"
        - "Install"
        - "Packages"
        - "Run"
        - "Build"
        - "Docker"
        - "Model"
        - "Other"
    validations:
      required: false

  - type: textarea
    attributes:
      label: Bug
      description: Please provide as much information as possible. Copy and paste console output and error messages including the _full_ traceback. Use [Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) to format text, code and logs. If necessary, include screenshots for visual elements only. Providing detailed information will help us resolve the issue more efficiently.
      placeholder: |
        💡 ProTip! Include as much information as possible (logs, tracebacks, screenshots, etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: Try the latest version before reporting a bug. If it's still present, please provide the logs to help us diagnose the problem.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        (Optional) We encourage you to submit a [Pull Request](https://github.com/dusty-nv/jetson-containers/pulls) (PR) to help improve jetson-containers for everyone, especially if you have a good understanding of how to implement a fix or feature.
      options:
        - label: Yes I'd like to help by submitting a PR!