blank_issues_enabled: true
contact_links:
  - name: 📄 Jetson Play Ground
    url: https://www.jetson-ai-lab.com/
    about: Full jetson-containers Demos
  - name: 💬 Forum
    url: https://forums.developer.nvidia.com/c/agx-autonomous-machines/jetson-embedded-systems/70
    about: Ask on jetson-containers Community Forum
  - name: 🎧 Discord
    url: https://discord.gg/qr8jbtYSsx
    about: Ask on jetson-containers Discord
