services:
  devpi-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '${DEVPI_PORT:-3141}:3141'
    volumes:
      - ${DEVPI_CACHE:-./cache/devpi}:/devpi
      - ./blacklist.txt:/etc/devpi/blacklist.txt:ro
    environment:
      DEVPI_MIRROR_BLACKLIST: '/etc/devpi/blacklist.txt'
      CLIENT_MAX_BODY_SIZE: '2048M'
      DEVPISERVER_SERVERDIR: /devpi
      DEVPI_PASSWORD: ${DEVPI_PASSWORD:-123}

  apt-server:
    build:
      context: apt
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '${APT_PORT:-8034}:80'
    volumes:
      - ${APT_ROOT:-./cache/apt}:/usr/share/nginx/html:ro
