server {
    listen 8080;
    root /usr/share/nginx/html;
    autoindex on;
    autoindex_exact_size off;
    autoindex_localtime on;
    client_max_body_size 4096M;

    dav_methods PUT DELETE;
    dav_access user:rw group:rw all:r;
    create_full_put_path on;
}
