name: "l4t-tensorflow-tf1_jp46"
run-name: "Build l4t-tensorflow:tf1 (JetPack 4.6)"
on:
  workflow_dispatch: {}
  push:
    branches:
      - 'dev'
    paths:
      - '.github/workflows/l4t-tensorflow-tf1_jp46.yml'
      - 'packages/l4t/l4t-tensorflow/*'
      - '!packages/l4t/l4t-tensorflow/README.md'
      - '!packages/l4t/l4t-tensorflow/docs.md'
      - 'packages/build-essential/*'
      - '!packages/build-essential/README.md'
      - '!packages/build-essential/docs.md'
      - 'packages/python/*'
      - '!packages/python/README.md'
      - '!packages/python/docs.md'
      - 'packages/numpy/*'
      - '!packages/numpy/README.md'
      - '!packages/numpy/docs.md'
      - 'packages/protobuf/protobuf_cpp/*'
      - '!packages/protobuf/protobuf_cpp/README.md'
      - '!packages/protobuf/protobuf_cpp/docs.md'
      - 'packages/tensorflow/*'
      - '!packages/tensorflow/README.md'
      - '!packages/tensorflow/docs.md'
      - 'packages/cuda/cuda/*'
      - '!packages/cuda/cuda/README.md'
      - '!packages/cuda/cuda/docs.md'
      - 'packages/cuda/cudnn/*'
      - '!packages/cuda/cudnn/README.md'
      - '!packages/cuda/cudnn/docs.md'
      - 'packages/opencv/*'
      - '!packages/opencv/README.md'
      - '!packages/opencv/docs.md'
      - 'packages/cuda/pycuda/*'
      - '!packages/cuda/pycuda/README.md'
      - '!packages/cuda/pycuda/docs.md'
jobs:
  l4t-tensorflow-tf1_jp46:
    runs-on: [self-hosted, jetson, jp46]
    steps:
      - run: |
         cat /etc/nv_tegra_release 
      - name: "Checkout ${{ github.repository }} SHA=${{ github.sha }}" 
        run: |
         echo "$RUNNER_WORKSPACE" 
         cd $RUNNER_WORKSPACE 
         git config --global user.email "dustinf@nvidia.com" 
         git config --global user.name "Dustin Franklin" 
         git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY || echo 'repo already cloned or another error encountered' 
         cd jetson-containers 
         git fetch origin 
         git checkout $GITHUB_SHA 
         git status 
         ls -a 
      - run: ./build.sh --name=runner/ --push=dustynv l4t-tensorflow:tf1