name: "l4t-text-generation_jp51"
run-name: "Build l4t-text-generation (JetPack 5.1)"
on:
  workflow_dispatch: {}
  push:
    branches:
      - 'dev'
    paths:
      - '.github/workflows/l4t-text-generation_jp51.yml'
      - 'packages/l4t/l4t-text-generation/*'
      - '!packages/l4t/l4t-text-generation/README.md'
      - '!packages/l4t/l4t-text-generation/docs.md'
      - 'packages/build-essential/*'
      - '!packages/build-essential/README.md'
      - '!packages/build-essential/docs.md'
      - 'packages/cuda/cuda/*'
      - '!packages/cuda/cuda/README.md'
      - '!packages/cuda/cuda/docs.md'
      - 'packages/cuda/cudnn/*'
      - '!packages/cuda/cudnn/README.md'
      - '!packages/cuda/cudnn/docs.md'
      - 'packages/python/*'
      - '!packages/python/README.md'
      - '!packages/python/docs.md'
      - 'packages/tensorrt/*'
      - '!packages/tensorrt/README.md'
      - '!packages/tensorrt/docs.md'
      - 'packages/numpy/*'
      - '!packages/numpy/README.md'
      - '!packages/numpy/docs.md'
      - 'packages/cmake/cmake_pip/*'
      - '!packages/cmake/cmake_pip/README.md'
      - '!packages/cmake/cmake_pip/docs.md'
      - 'packages/onnx/*'
      - '!packages/onnx/README.md'
      - '!packages/onnx/docs.md'
      - 'packages/pytorch/*'
      - '!packages/pytorch/README.md'
      - '!packages/pytorch/docs.md'
      - 'packages/pytorch/torchvision/*'
      - '!packages/pytorch/torchvision/README.md'
      - '!packages/pytorch/torchvision/docs.md'
      - 'packages/llm/huggingface_hub/*'
      - '!packages/llm/huggingface_hub/README.md'
      - '!packages/llm/huggingface_hub/docs.md'
      - 'packages/rust/*'
      - '!packages/rust/README.md'
      - '!packages/rust/docs.md'
      - 'packages/llm/transformers/*'
      - '!packages/llm/transformers/README.md'
      - '!packages/llm/transformers/docs.md'
      - 'packages/llm/bitsandbytes/*'
      - '!packages/llm/bitsandbytes/README.md'
      - '!packages/llm/bitsandbytes/docs.md'
      - 'packages/llm/auto_gptq/*'
      - '!packages/llm/auto_gptq/README.md'
      - '!packages/llm/auto_gptq/docs.md'
      - 'packages/llm/gptq-for-llama/*'
      - '!packages/llm/gptq-for-llama/README.md'
      - '!packages/llm/gptq-for-llama/docs.md'
      - 'packages/llm/exllama/*'
      - '!packages/llm/exllama/README.md'
      - '!packages/llm/exllama/docs.md'
      - 'packages/llm/exllama/*'
      - '!packages/llm/exllama/README.md'
      - '!packages/llm/exllama/docs.md'
      - 'packages/llm/llama_cpp/*'
      - '!packages/llm/llama_cpp/README.md'
      - '!packages/llm/llama_cpp/docs.md'
      - 'packages/llm/awq/*'
      - '!packages/llm/awq/README.md'
      - '!packages/llm/awq/docs.md'
jobs:
  l4t-text-generation_jp51:
    runs-on: [self-hosted, jetson, jp51]
    steps:
      - run: |
         cat /etc/nv_tegra_release 
      - name: "Checkout ${{ github.repository }} SHA=${{ github.sha }}" 
        run: |
         echo "$RUNNER_WORKSPACE" 
         cd $RUNNER_WORKSPACE 
         git config --global user.email "dustinf@nvidia.com" 
         git config --global user.name "Dustin Franklin" 
         git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY || echo 'repo already cloned or another error encountered' 
         cd jetson-containers 
         git fetch origin 
         git checkout $GITHUB_SHA 
         git status 
         ls -a 
      - run: ./build.sh --name=runner/ --push=dustynv l4t-text-generation