name: "ros-melodic-desktop_jp46"
run-name: "Build ros:melodic-desktop (JetPack 4.6)"
on:
  workflow_dispatch: {}
  push:
    branches:
      - 'dev'
    paths:
      - '.github/workflows/ros-melodic-desktop_jp46.yml'
      - 'packages/ros/*'
      - '!packages/ros/README.md'
      - '!packages/ros/docs.md'
      - 'packages/build-essential/*'
      - '!packages/build-essential/README.md'
      - '!packages/build-essential/docs.md'
      - 'packages/cmake/cmake_apt/*'
      - '!packages/cmake/cmake_apt/README.md'
      - '!packages/cmake/cmake_apt/docs.md'
      - 'packages/cuda/cuda/*'
      - '!packages/cuda/cuda/README.md'
      - '!packages/cuda/cuda/docs.md'
      - 'packages/cuda/cudnn/*'
      - '!packages/cuda/cudnn/README.md'
      - '!packages/cuda/cudnn/docs.md'
      - 'packages/python/*'
      - '!packages/python/README.md'
      - '!packages/python/docs.md'
      - 'packages/tensorrt/*'
      - '!packages/tensorrt/README.md'
      - '!packages/tensorrt/docs.md'
      - 'packages/cmake/cmake_pip/*'
      - '!packages/cmake/cmake_pip/README.md'
      - '!packages/cmake/cmake_pip/docs.md'
jobs:
  ros-melodic-desktop_jp46:
    runs-on: [self-hosted, jetson, jp46]
    steps:
      - run: |
         cat /etc/nv_tegra_release 
      - name: "Checkout ${{ github.repository }} SHA=${{ github.sha }}" 
        run: |
         echo "$RUNNER_WORKSPACE" 
         cd $RUNNER_WORKSPACE 
         git config --global user.email "dustinf@nvidia.com" 
         git config --global user.name "Dustin Franklin" 
         git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY || echo 'repo already cloned or another error encountered' 
         cd jetson-containers 
         git fetch origin 
         git checkout $GITHUB_SHA 
         git status 
         ls -a 
      - run: ./build.sh --name=runner/ --push=dustynv ros:melodic-desktop